// Archivo con las 500 frases para la funcionalidad "Cómo suena en el mundo real"
export interface FamilyContext {
  name: string
  fullName: string
  parent1: string
  parent2: string
  sibling: string
  allFamily: string
  lastName1: string
  lastName2: string
}

export const generateAllPhrases = (ctx: FamilyContext) => [
  // EN CASA (80 frases)
  { title: '🏠 En casa', text: `¡${ctx.name}, a cenar! Que se enfría la comida.` },
  { title: '🏠 En casa', text: `${ctx.name}, ¿puedes bajar la basura antes de salir?` },
  { title: '🏠 En casa', text: `${ctx.name}, recoge tu habitación, que parece una leonera.` },
  { title: '🏠 En casa', text: `¿${ctx.name}? ¿Dónde te has metido? ¡La comida está lista!` },
  { title: '🏠 En casa', text: `${ctx.name}, apaga las luces cuando salgas de tu cuarto.` },
  { title: '🏠 En casa', text: `${ctx.parent1} llama a ${ctx.name} para que venga a ayudar.` },
  { title: '🏠 En casa', text: `${ctx.name}, dile a ${ctx.sibling} que baje a cenar.` },
  { title: '🏠 En casa', text: `${ctx.parent2}, ¿has visto a ${ctx.name}? No le encuentro.` },
  { title: '🏠 En casa', text: `${ctx.name} y ${ctx.sibling}, dejad de pelearos ahora mismo.` },
  { title: '🏠 En casa', text: `¡${ctx.allFamily}! Venid todos, vamos a hacer una foto familiar.` },
  { title: '🏠 En casa', text: `${ctx.name}, ponte el pijama y lávate los dientes.` },
  { title: '🏠 En casa', text: `${ctx.name}, ayuda a ${ctx.parent1} a poner la mesa.` },
  { title: '🏠 En casa', text: `¿${ctx.name}? Tu abuela te ha traído un regalo.` },
  { title: '🏠 En casa', text: `${ctx.name}, dale las buenas noches a ${ctx.parent2}.` },
  { title: '🏠 En casa', text: `${ctx.name}, ordena tus juguetes antes de irte a dormir.` },
  { title: '🏠 En casa', text: `¡${ctx.name}! No corras por el pasillo, que te vas a caer.` },
  { title: '🏠 En casa', text: `${ctx.name}, pregúntale a ${ctx.sibling} si quiere merendar.` },
  { title: '🏠 En casa', text: `${ctx.parent1} y ${ctx.parent2} están orgullosos de ${ctx.name}.` },
  { title: '🏠 En casa', text: `${ctx.name}, saca al perro a pasear, por favor.` },
  { title: '🏠 En casa', text: `¿${ctx.name}? ${ctx.parent2} dice que le ayudes con la compra.` },
  { title: '🏠 En casa', text: `${ctx.name}, cierra la puerta con cuidado al salir.` },
  { title: '🏠 En casa', text: `${ctx.name}, comparte los juguetes con ${ctx.sibling}.` },
  { title: '🏠 En casa', text: `${ctx.parent1} busca a ${ctx.name} para darle su medicamento.` },
  { title: '🏠 En casa', text: `${ctx.name}, no olvides regar las plantas del jardín.` },
  { title: '🏠 En casa', text: `¡${ctx.name}! Baja el volumen de la tele, que molesta.` },
  { title: '🏠 En casa', text: `${ctx.name}, ${ctx.parent2} te está llamando desde la cocina.` },
  { title: '🏠 En casa', text: `${ctx.name} y ${ctx.sibling} tienen que recoger sus habitaciones.` },
  { title: '🏠 En casa', text: `${ctx.name}, abraza a ${ctx.parent1} que está triste.` },
  { title: '🏠 En casa', text: `${ctx.name}, dale un beso a tu abuela que se va ya.` },
  { title: '🏠 En casa', text: `¡${ctx.name}! No saltes en el sofá, que lo rompes.` },
  { title: '🏠 En casa', text: `${ctx.name}, pregunta a ${ctx.parent2} si puedes salir a jugar.` },
  { title: '🏠 En casa', text: `${ctx.parent1} quiere hablar con ${ctx.name} un momento.` },
  { title: '🏠 En casa', text: `${ctx.name}, cámbiate de ropa que está toda sucia.` },
  { title: '🏠 En casa', text: `${ctx.name}, limpia tu cuarto antes de que lleguen visitas.` },
  { title: '🏠 En casa', text: `¡${ctx.name}! No comas más galletas antes de cenar.` },
  { title: '🏠 En casa', text: `${ctx.name}, guarda la ropa limpia en el armario.` },
  { title: '🏠 En casa', text: `${ctx.name}, dile a ${ctx.sibling} que venga a comer.` },
  { title: '🏠 En casa', text: `${ctx.parent2} prepara el almuerzo favorito de ${ctx.name}.` },
  { title: '🏠 En casa', text: `${ctx.name}, cuelga el abrigo en el perchero.` },
  { title: '🏠 En casa', text: `${ctx.name}, no molestes que ${ctx.parent1} está trabajando.` },
  { title: '🏠 En casa', text: `¡${ctx.name}! Ven a ver esta foto de cuando eras pequeño.` },
  { title: '🏠 En casa', text: `${ctx.name}, ayuda a ${ctx.sibling} con los deberes.` },
  { title: '🏠 En casa', text: `${ctx.name}, recoge la mesa cuando termines de comer.` },
  { title: '🏠 En casa', text: `${ctx.parent1} lleva a ${ctx.name} al parque esta tarde.` },
  { title: '🏠 En casa', text: `${ctx.name}, no dejes la mochila tirada en medio.` },
  { title: '🏠 En casa', text: `${ctx.name}, date prisa que llegamos tarde al cole.` },
  { title: '🏠 En casa', text: `${ctx.parent2} peina a ${ctx.name} antes de salir.` },
  { title: '🏠 En casa', text: `${ctx.name}, lávate las manos antes de tocar nada.` },
  { title: '🏠 En casa', text: `${ctx.name}, no hagas ruido que ${ctx.sibling} está durmiendo.` },
  { title: '🏠 En casa', text: `¡${ctx.name}! Tu comida favorita está lista.` },
  { title: '🏠 En casa', text: `${ctx.name}, baja la escalera despacio, sin correr.` },
  { title: '🏠 En casa', text: `${ctx.parent1} regaña a ${ctx.name} por no ordenar.` },
  { title: '🏠 En casa', text: `${ctx.name}, dale las gracias a ${ctx.parent2}.` },
  { title: '🏠 En casa', text: `${ctx.name}, no uses el móvil en la mesa.` },
  { title: '🏠 En casa', text: `${ctx.name} y ${ctx.sibling}, sentaos bien en la mesa.` },
  { title: '🏠 En casa', text: `${ctx.name}, cierra el grifo que malgastas agua.` },
  { title: '🏠 En casa', text: `${ctx.parent2} abraza a ${ctx.name} antes de dormir.` },
  { title: '🏠 En casa', text: `${ctx.name}, no toques eso que está caliente.` },
  { title: '🏠 En casa', text: `${ctx.name}, prepara la mochila para mañana.` },
  { title: '🏠 En casa', text: `${ctx.parent1} felicita a ${ctx.name} por portarse bien.` },
  { title: '🏠 En casa', text: `${ctx.name}, ponte las zapatillas antes de bajar.` },
  { title: '🏠 En casa', text: `${ctx.name}, abre la ventana que huele a cerrado.` },
  { title: '🏠 En casa', text: `${ctx.parent2} llama a ${ctx.name} para merendar.` },
  { title: '🏠 En casa', text: `${ctx.name}, no le pegues a ${ctx.sibling}.` },
  { title: '🏠 En casa', text: `${ctx.name}, sube las escaleras de una en una.` },
  { title: '🏠 En casa', text: `${ctx.parent1} juega con ${ctx.name} en el salón.` },
  { title: '🏠 En casa', text: `${ctx.name}, quítate los zapatos al entrar.` },
  { title: '🏠 En casa', text: `${ctx.name}, no grites que ${ctx.parent2} tiene dolor de cabeza.` },
  { title: '🏠 En casa', text: `${ctx.name}, dale un abrazo a ${ctx.sibling}.` },
  { title: '🏠 En casa', text: `${ctx.name}, termina toda la comida del plato.` },
  { title: '🏠 En casa', text: `${ctx.parent1} lee un cuento a ${ctx.name} antes de dormir.` },
  { title: '🏠 En casa', text: `${ctx.name}, no toques los enchufes, es peligroso.` },
  { title: '🏠 En casa', text: `${ctx.name}, ayúdame a doblar esta ropa.` },
  { title: '🏠 En casa', text: `${ctx.parent2} busca a ${ctx.name} para darle un beso.` },
  { title: '🏠 En casa', text: `${ctx.name}, comparte la tablet con ${ctx.sibling}.` },
  { title: '🏠 En casa', text: `${ctx.name}, no tires la comida que hay niños que no tienen.` },
  { title: '🏠 En casa', text: `${ctx.parent1} enseña a ${ctx.name} a atarse los cordones.` },
  { title: '🏠 En casa', text: `${ctx.name}, espera a ${ctx.sibling} para jugar juntos.` },
  { title: '🏠 En casa', text: `${ctx.name}, pídele perdón a ${ctx.parent2}.` },

  // EN EL COLEGIO (60 frases)
  { title: '🏫 En el colegio', text: `${ctx.name}, ¿puedes leer el siguiente párrafo?` },
  { title: '🏫 En el colegio', text: `Muy bien, ${ctx.name}. Excelente trabajo en el examen.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, ¿has hecho los deberes de matemáticas?` },
  { title: '🏫 En el colegio', text: `El delegado de clase será ${ctx.name}. ¡Felicidades!` },
  { title: '🏫 En el colegio', text: `${ctx.name}, por favor, sal a la pizarra.` },
  { title: '🏫 En el colegio', text: `${ctx.name} ${ctx.lastName1}, preséntate ante la clase.` },
  { title: '🏫 En el colegio', text: `Llamamos a los padres de ${ctx.name}: ${ctx.parent1} y ${ctx.parent2}.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, tu hermano ${ctx.sibling} está en infantil.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, no copies de tu compañero.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, reparte los cuadernos a tus compañeros.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, ve al despacho del director.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, felicidades por tu nota en el examen.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, siéntate bien y presta atención.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, guarda silencio durante el examen.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, lee en voz alta para todos.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, ayuda a ${ctx.sibling} a buscar su mochila.` },
  { title: '🏫 En el colegio', text: `Los padres de ${ctx.name} han venido a la reunión.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, sal al recreo con tus compañeros.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, no hables mientras explico.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, devuelve ese libro a la biblioteca.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, ven aquí que te voy a explicar.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, borra la pizarra, por favor.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, tienes que mejorar tu letra.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, no corras por los pasillos.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, recoge tus cosas que ya es la hora.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, espera a que ${ctx.parent1} venga a recogerte.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, haz la fila para entrar al aula.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, comparte los colores con tus compañeros.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, no grites en clase.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, sube al autobús escolar.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, trabaja en equipo con tus compañeros.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, eres el encargado de repartir material hoy.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, no uses el móvil en clase.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, levanta la mano antes de hablar.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, ven a mi despacho después de clase.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, copia los apuntes de la pizarra.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, no tires papeles al suelo.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, dile a ${ctx.parent2} que firme la nota.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, ten cuidado en el laboratorio.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, participa más en clase.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, felicidades por tu presentación.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, ordena tu pupitre.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, no llegues tarde mañana.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, enséñame tu tarea de ayer.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, espera tu turno en el comedor.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, guarda tu estuche en la mochila.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, respeta a tus profesores.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, concentrate en la explicación.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, ve a educación física.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, lleva este aviso a ${ctx.parent1}.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, no hables con ${ctx.sibling} en el recreo.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, limpia tu mesa antes de salir.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, no te olvides de tu chaqueta.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, felicidades por tu diploma.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, vas a representar al colegio en el concurso.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, pregunta si no entiendes algo.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, ayuda al nuevo alumno a adaptarse.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, tráeme la justificación firmada.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, no pelees con tus compañeros.` },
  { title: '🏫 En el colegio', text: `${ctx.name}, espera a ${ctx.sibling} a la salida.` },

  // CON HERMANOS Y FAMILIA (70 frases)
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.name}, juega con ${ctx.sibling} un rato.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.parent1} lleva a ${ctx.name} y ${ctx.sibling} al parque.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `¿Dónde están ${ctx.name} y ${ctx.sibling}?` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.parent2} prepara la merienda para ${ctx.name} y ${ctx.sibling}.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.name}, no molestes a ${ctx.sibling} mientras estudia.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.name}, presta tus juguetes a ${ctx.sibling}.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.parent1} y ${ctx.parent2} están orgullosos de ${ctx.name}.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.name}, dale la mano a ${ctx.sibling} para cruzar.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `¡${ctx.allFamily}! Es hora de cenar en familia.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.name}, cuida de ${ctx.sibling} mientras vuelvo.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.parent1} enseña a ${ctx.name} a montar en bici.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.name}, comparte la tablet con ${ctx.sibling}.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.parent2} baña a ${ctx.name} y ${ctx.sibling}.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.name}, ayuda a ${ctx.sibling} a vestirse.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.name} y ${ctx.sibling}, dejar de discutir ya.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.parent1} juega al fútbol con ${ctx.name}.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.name}, espera a ${ctx.sibling} para ir juntos.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.parent2} llama a ${ctx.name} para hacer las tareas.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.name}, sé generoso con ${ctx.sibling}.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `¡${ctx.name}! ${ctx.parent1} te está buscando.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.name} ${ctx.lastName1} ${ctx.lastName2}, ven aquí inmediatamente.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.parent1} y ${ctx.parent2} os quieren mucho, ${ctx.name}.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.name}, ve a buscar a ${ctx.sibling} a su cuarto.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.parent2} canta una canción a ${ctx.name}.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.name}, dale un beso a ${ctx.parent1}.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.name} y ${ctx.sibling}, ordenad vuestros cuartos.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.parent1} lleva a ${ctx.name} al médico.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.name}, pregunta a ${ctx.parent2} si puedes salir.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.name}, comparte el postre con ${ctx.sibling}.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.parent1} abraza a ${ctx.name} con cariño.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.name}, ve con ${ctx.sibling} a jugar fuera.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.parent2} prepara el desayuno para ${ctx.name}.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.name}, no te burles de ${ctx.sibling}.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.parent1} enseña a ${ctx.name} a nadar.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.name}, llama a ${ctx.parent2} para comer.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.name} y ${ctx.sibling}, jugad en paz.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.parent1} lleva a ${ctx.name} al cumpleaños.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.name}, pide perdón a ${ctx.sibling}.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.parent2} peina a ${ctx.name} para el colegio.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.name}, ayuda a ${ctx.parent1} con la cena.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `¡${ctx.allFamily}! Sonreíd para la foto.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.name}, ve a la tienda con ${ctx.parent2}.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.parent1} lee un cuento a ${ctx.name} y ${ctx.sibling}.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.name}, enséñale a ${ctx.sibling} cómo se hace.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.parent2} llama a ${ctx.name} para hablar.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.name}, sé paciente con ${ctx.sibling}.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.parent1} felicita a ${ctx.name} por sus notas.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.name}, acompaña a ${ctx.sibling} al baño.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.parent2} prepara un regalo para ${ctx.name}.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.name}, no pegues a ${ctx.sibling}.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.parent1} lleva a ${ctx.name} a entrenar.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.name}, dale las buenas noches a todos.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.parent2} canta con ${ctx.name} en el coche.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.name}, protege a ${ctx.sibling}.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.parent1} juega a las cartas con ${ctx.name}.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.name}, avisa a ${ctx.sibling} que vamos a salir.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.parent2} consuela a ${ctx.name} cuando llora.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.name}, quieres mucho a ${ctx.parent1}.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.parent1} y ${ctx.parent2} cuidan de ${ctx.name}.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.name}, recoge la habitación que viene ${ctx.sibling}.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.parent2} prepara la fiesta de ${ctx.name}.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.name}, dale un abrazo a ${ctx.parent1}.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.name} y ${ctx.sibling}, venid a ver la tele.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.parent1} enseña a ${ctx.name} a cocinar.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.name}, pregunta a ${ctx.parent2} por tus abuelos.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.name}, juega con ${ctx.sibling} al escondite.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.parent1} lleva a ${ctx.name} a la playa.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.name}, ayuda a ${ctx.parent2} con las bolsas.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `${ctx.name}, eres el mayor, da ejemplo a ${ctx.sibling}.` },
  { title: '👨‍👩‍👧‍👦 En familia', text: `La familia ${ctx.lastName1} ${ctx.lastName2} al completo: ${ctx.allFamily}.` },

  // DOCUMENTOS OFICIALES Y APELLIDOS (60 frases)
  { title: '📄 Documentos oficiales', text: `Nombre completo: ${ctx.fullName}.` },
  { title: '📄 Documentos oficiales', text: `DNI a nombre de ${ctx.fullName}.` },
  { title: '📄 Documentos oficiales', text: `Pasaporte de ${ctx.fullName}. Válido hasta 2035.` },
  { title: '📄 Documentos oficiales', text: `Tarjeta sanitaria: ${ctx.name} ${ctx.lastName1} ${ctx.lastName2}.` },
  { title: '📄 Documentos oficiales', text: `Certificado de nacimiento de ${ctx.fullName}.` },
  { title: '📄 Documentos oficiales', text: `Familia ${ctx.lastName1} ${ctx.lastName2}: ${ctx.allFamily}.` },
  { title: '📄 Documentos oficiales', text: `Matrícula escolar para ${ctx.fullName}.` },
  { title: '📄 Documentos oficiales', text: `Carné de biblioteca: ${ctx.name} ${ctx.lastName1}.` },
  { title: '📄 Documentos oficiales', text: `Informe médico del paciente ${ctx.fullName}.` },
  { title: '📄 Documentos oficiales', text: `Cuenta bancaria a nombre de ${ctx.fullName}.` },
  { title: '📄 Documentos oficiales', text: `Seguro médico de ${ctx.name} ${ctx.lastName1} ${ctx.lastName2}.` },
  { title: '📄 Documentos oficiales', text: `Solicitud universitaria: ${ctx.fullName}.` },
  { title: '📄 Documentos oficiales', text: `Permiso de conducir de ${ctx.fullName}.` },
  { title: '📄 Documentos oficiales', text: `Contrato laboral para ${ctx.fullName}.` },
  { title: '📄 Documentos oficiales', text: `Título universitario a nombre de ${ctx.fullName}.` },
  { title: '📄 Documentos oficiales', text: `Certificado digital de ${ctx.name} ${ctx.lastName1}.` },
  { title: '📄 Documentos oficiales', text: `Nómina del empleado ${ctx.fullName}.` },
  { title: '📄 Documentos oficiales', text: `Registro civil: ${ctx.name} ${ctx.lastName1} ${ctx.lastName2}.` },
  { title: '📄 Documentos oficiales', text: `Hijos de ${ctx.parent1} ${ctx.lastName1}: ${ctx.name} y ${ctx.sibling}.` },
  { title: '📄 Documentos oficiales', text: `Receta médica para ${ctx.fullName}.` },
  { title: '📄 Documentos oficiales', text: `Cita previa: ${ctx.name} ${ctx.lastName1} ${ctx.lastName2}.` },
  { title: '📄 Documentos oficiales', text: `Reserva de vuelo a nombre de ${ctx.fullName}.` },
  { title: '📄 Documentos oficiales', text: `Expediente académico de ${ctx.fullName}.` },
  { title: '📄 Documentos oficiales', text: `Certificado de antecedentes penales: ${ctx.fullName}.` },
  { title: '📄 Documentos oficiales', text: `Escritura de propiedad: ${ctx.fullName}.` },
  { title: '📄 Documentos oficiales', text: `Testamento de ${ctx.parent1} y ${ctx.parent2}: herederos ${ctx.name} y ${ctx.sibling}.` },
  { title: '📄 Documentos oficiales', text: `Padrón municipal: ${ctx.fullName}.` },
  { title: '📄 Documentos oficiales', text: `Licencia profesional de ${ctx.name} ${ctx.lastName1}.` },
  { title: '📄 Documentos oficiales', text: `Póliza de seguro del hogar: ${ctx.fullName}.` },
  { title: '📄 Documentos oficiales', text: `Certificado de empadronamiento: ${ctx.fullName}.` },
  { title: '📄 Documentos oficiales', text: `Declaración de la renta de ${ctx.fullName}.` },
  { title: '📄 Documentos oficiales', text: `Libro de familia ${ctx.lastName1} ${ctx.lastName2}.` },
  { title: '📄 Documentos oficiales', text: `Tarjeta de embarque: ${ctx.name} ${ctx.lastName1}.` },
  { title: '📄 Documentos oficiales', text: `Contrato de alquiler a nombre de ${ctx.fullName}.` },
  { title: '📄 Documentos oficiales', text: `Factura eléctrica: ${ctx.fullName}.` },
  { title: '📄 Documentos oficiales', text: `Membresía del gimnasio: ${ctx.name} ${ctx.lastName1} ${ctx.lastName2}.` },
  { title: '📄 Documentos oficiales', text: `Certificado de matrimonio de ${ctx.parent1} y ${ctx.parent2}.` },
  { title: '📄 Documentos oficiales', text: `Solicitud de beca universitaria: ${ctx.fullName}.` },
  { title: '📄 Documentos oficiales', text: `Permiso de viaje para menor: ${ctx.name} ${ctx.lastName1}.` },
  { title: '📄 Documentos oficiales', text: `Certificado de defunción del abuelo de ${ctx.name}.` },
  { title: '📄 Documentos oficiales', text: `Póliza de vida a favor de ${ctx.name} y ${ctx.sibling}.` },
  { title: '📄 Documentos oficiales', text: `Licencia de obras: vivienda ${ctx.lastName1} ${ctx.lastName2}.` },
  { title: '📄 Documentos oficiales', text: `Certificado médico de ${ctx.fullName}.` },
  { title: '📄 Documentos oficiales', text: `Visa de estudiante para ${ctx.name} ${ctx.lastName1}.` },
  { title: '📄 Documentos oficiales', text: `Seguro de coche de ${ctx.fullName}.` },
  { title: '📄 Documentos oficiales', text: `Afiliación a la seguridad social: ${ctx.fullName}.` },
  { title: '📄 Documentos oficiales', text: `Certificado de notas de ${ctx.name} ${ctx.lastName1} ${ctx.lastName2}.` },
  { title: '📄 Documentos oficiales', text: `Permiso de residencia: ${ctx.fullName}.` },
  { title: '📄 Documentos oficiales', text: `Contrato de compraventa firmado por ${ctx.fullName}.` },
  { title: '📄 Documentos oficiales', text: `Acta notarial: comparece ${ctx.fullName}.` },
  { title: '📄 Documentos oficiales', text: `Demanda judicial presentada por ${ctx.fullName}.` },
  { title: '📄 Documentos oficiales', text: `Sentencia a favor de ${ctx.name} ${ctx.lastName1}.` },
  { title: '📄 Documentos oficiales', text: `Poder notarial otorgado a ${ctx.fullName}.` },
  { title: '📄 Documentos oficiales', text: `Acta de matrimonio: ${ctx.parent1} y ${ctx.parent2} ${ctx.lastName1}.` },
  { title: '📄 Documentos oficiales', text: `Certificado de adopción de ${ctx.name} por ${ctx.parent1} y ${ctx.parent2}.` },
  { title: '📄 Documentos oficiales', text: `Registro de propiedad intelectual: ${ctx.fullName}.` },
  { title: '📄 Documentos oficiales', text: `Certificado de buena conducta: ${ctx.fullName}.` },
  { title: '📄 Documentos oficiales', text: `Informe psicológico del menor ${ctx.name} ${ctx.lastName1}.` },
  { title: '📄 Documentos oficiales', text: `Tutela legal ejercida por ${ctx.parent1} sobre ${ctx.name}.` },
  { title: '📄 Documentos oficiales', text: `Árbol genealógico de la familia ${ctx.lastName1} ${ctx.lastName2}.` },

  // GRADUACIÓN Y EVENTOS FORMALES (40 frases)
  { title: '🎓 Graduación', text: `Con todos ustedes, ${ctx.fullName}. ¡Felicidades!` },
  { title: '🎓 Graduación', text: `El premio al mejor expediente es para ${ctx.fullName}.` },
  { title: '🎓 Graduación', text: `Doctor ${ctx.fullName}, enhorabuena por su doctorado.` },
  { title: '🎓 Graduación', text: `Mención de honor para el estudiante ${ctx.fullName}.` },
  { title: '🎓 Graduación', text: `Licenciado ${ctx.fullName}, pase a recoger su título.` },
  { title: '🎓 Graduación', text: `Graduado en Medicina: ${ctx.name} ${ctx.lastName1} ${ctx.lastName2}.` },
  { title: '🎓 Graduación', text: `Ingeniero ${ctx.name} ${ctx.lastName1}, felicidades por su título.` },
  { title: '🎓 Graduación', text: `Máster en Derecho por ${ctx.fullName}.` },
  { title: '🎓 Graduación', text: `Profesor ${ctx.fullName}, tome posesión de su cátedra.` },
  { title: '🎓 Graduación', text: `Tesis doctoral defendida por ${ctx.fullName}.` },
  { title: '🎓 Graduación', text: `Orgullo de ${ctx.parent1} y ${ctx.parent2}: ${ctx.name} se gradúa.` },
  { title: '🎓 Graduación', text: `Premio extraordinario para ${ctx.name} ${ctx.lastName1}.` },
  { title: '🎓 Graduación', text: `Cum Laude: ${ctx.fullName}.` },
  { title: '🎓 Graduación', text: `Arquitecto ${ctx.fullName}, su proyecto es brillante.` },
  { title: '🎓 Graduación', text: `Beca de investigación otorgada a ${ctx.fullName}.` },
  { title: '🎓 Graduación', text: `Post-doctorado en Harvard: ${ctx.name} ${ctx.lastName1}.` },
  { title: '🎓 Graduación', text: `Catedrático ${ctx.fullName}, bienvenido al claustro.` },
  { title: '🎓 Graduación', text: `Matrícula de honor para ${ctx.name} ${ctx.lastName1} ${ctx.lastName2}.` },
  { title: '🎓 Graduación', text: `Premio Nacional de investigación: ${ctx.fullName}.` },
  { title: '🎓 Graduación', text: `Doctor Honoris Causa: Don/Doña ${ctx.fullName}.` },
  { title: '🎓 Graduación', text: `Mejor estudiante del año: ${ctx.name} ${ctx.lastName1}.` },
  { title: '🎓 Graduación', text: `Discurso de graduación a cargo de ${ctx.fullName}.` },
  { title: '🎓 Graduación', text: `MBA por ${ctx.name} ${ctx.lastName1} ${ctx.lastName2}.` },
  { title: '🎓 Graduación', text: `Licenciatura con honores: ${ctx.fullName}.` },
  { title: '🎓 Graduación', text: `Farmacéutico ${ctx.fullName}, felicidades.` },
  { title: '🎓 Graduación', text: `Psicólogo colegiado: ${ctx.name} ${ctx.lastName1}.` },
  { title: '🎓 Graduación', text: `Abogado ${ctx.fullName}, bienvenido al Colegio de Abogados.` },
  { title: '🎓 Graduación', text: `Premio fin de carrera: ${ctx.name} ${ctx.lastName1} ${ctx.lastName2}.` },
  { title: '🎓 Graduación', text: `Enfermero titulado: ${ctx.fullName}.` },
  { title: '🎓 Graduación', text: `Veterinario ${ctx.name} ${ctx.lastName1}, felicidades.` },
  { title: '🎓 Graduación', text: `Master en Finanzas: ${ctx.fullName}.` },
  { title: '🎓 Graduación', text: `Economista colegiado: ${ctx.name} ${ctx.lastName1} ${ctx.lastName2}.` },
  { title: '🎓 Graduación', text: `Periodista titulado: ${ctx.fullName}.` },
  { title: '🎓 Graduación', text: `Ingeniero Industrial ${ctx.name} ${ctx.lastName1}.` },
  { title: '🎓 Graduación', text: `Químico: ${ctx.fullName}, suma cum laude.` },
  { title: '🎓 Graduación', text: `Biólogo ${ctx.name} ${ctx.lastName1} ${ctx.lastName2}.` },
  { title: '🎓 Graduación', text: `Físico ${ctx.fullName}, premio a la excelencia.` },
  { title: '🎓 Graduación', text: `Matemático ${ctx.name} ${ctx.lastName1}, medalla de oro.` },
  { title: '🎓 Graduación', text: `Historiador del Arte: ${ctx.fullName}.` },
  { title: '🎓 Graduación', text: `Filólogo ${ctx.name} ${ctx.lastName1} ${ctx.lastName2}, cum laude.` },

  // EVENTOS SOCIALES (40 frases)
  { title: '🎂 Celebraciones', text: `¡Feliz cumpleaños, ${ctx.name}! Que cumplas muchos más.` },
  { title: '🎂 Celebraciones', text: `¡Por ${ctx.name}! ¡Hip, hip, hurra!` },
  { title: '🎂 Celebraciones', text: `${ctx.name}, sopla las velas y pide un deseo.` },
  { title: '🎂 Celebraciones', text: `Esta fiesta es en honor a ${ctx.name}. ¡Bienvenidos!` },
  { title: '🎂 Celebraciones', text: `${ctx.name} ha aprobado todo. ¡Brindemos!` },
  { title: '🎂 Celebraciones', text: `La comunión de ${ctx.name} ${ctx.lastName1} ${ctx.lastName2}.` },
  { title: '🎂 Celebraciones', text: `Bautizo de ${ctx.name}, hijo de ${ctx.parent1} y ${ctx.parent2}.` },
  { title: '🎂 Celebraciones', text: `${ctx.name} cumple 18 años. ¡Ya es mayor de edad!` },
  { title: '🎂 Celebraciones', text: `Fiesta sorpresa para ${ctx.name}. ¡Silencio!` },
  { title: '🎂 Celebraciones', text: `${ctx.parent1} y ${ctx.parent2} organizan la fiesta de ${ctx.name}.` },
  { title: '🎂 Celebraciones', text: `Todos cantamos el cumpleaños feliz a ${ctx.name}.` },
  { title: '🎂 Celebraciones', text: `${ctx.name}, abre los regalos que te han traído.` },
  { title: '🎂 Celebraciones', text: `La tarta tiene el nombre de ${ctx.name} escrito.` },
  { title: '🎂 Celebraciones', text: `${ctx.name} invita a ${ctx.sibling} a su fiesta.` },
  { title: '🎂 Celebraciones', text: `Confirmación de ${ctx.name} ${ctx.lastName1}.` },
  { title: '🎂 Celebraciones', text: `Bar mitzvah de ${ctx.name} ${ctx.lastName1} ${ctx.lastName2}.` },
  { title: '🎂 Celebraciones', text: `Quinceañera de ${ctx.name}. ¡Felicidades!` },
  { title: '🎂 Celebraciones', text: `Graduación de bachillerato: ${ctx.name} ${ctx.lastName1}.` },
  { title: '🎂 Celebraciones', text: `${ctx.name}, has sacado sobresaliente. ¡A celebrarlo!` },
  { title: '🎂 Celebraciones', text: `Aniversario de la familia ${ctx.lastName1} ${ctx.lastName2}.` },
  { title: '🎂 Celebraciones', text: `Boda de ${ctx.name} ${ctx.lastName1}. ¡Enhorabuena!` },
  { title: '🎂 Celebraciones', text: `${ctx.name} y su pareja se casan. ¡Viva los novios!` },
  { title: '🎂 Celebraciones', text: `Pedida de mano: ${ctx.name} ha dicho que sí.` },
  { title: '🎂 Celebraciones', text: `${ctx.name}, ¡felicidades por tu nuevo trabajo!` },
  { title: '🎂 Celebraciones', text: `${ctx.parent1} y ${ctx.parent2} celebran el éxito de ${ctx.name}.` },
  { title: '🎂 Celebraciones', text: `${ctx.name} inaugura su propio negocio. ¡Bravo!` },
  { title: '🎂 Celebraciones', text: `Premio al mérito profesional: ${ctx.fullName}.` },
  { title: '🎂 Celebraciones', text: `${ctx.name}, te han ascendido. ¡Qué alegría!` },
  { title: '🎂 Celebraciones', text: `Homenaje a ${ctx.name} por sus 25 años en la empresa.` },
  { title: '🎂 Celebraciones', text: `${ctx.name} se jubila. ¡Gracias por todo!` },
  { title: '🎂 Celebraciones', text: `Bodas de oro de ${ctx.parent1} y ${ctx.parent2}. ${ctx.name} lo celebra con ellos.` },
  { title: '🎂 Celebraciones', text: `${ctx.name}, ¡eres padre/madre! Enhorabuena.` },
  { title: '🎂 Celebraciones', text: `Bautizo del hijo de ${ctx.name} ${ctx.lastName1}.` },
  { title: '🎂 Celebraciones', text: `${ctx.name}, has ganado el premio. ¡Increíble!` },
  { title: '🎂 Celebraciones', text: `Medalla al valor civil para ${ctx.fullName}.` },
  { title: '🎂 Celebraciones', text: `${ctx.name} recibe el reconocimiento público.` },
  { title: '🎂 Celebraciones', text: `Homenaje a ${ctx.name} por su labor social.` },
  { title: '🎂 Celebraciones', text: `${ctx.name}, eres el ciudadano del año. ¡Felicidades!` },
  { title: '🎂 Celebraciones', text: `Premio humanitario para ${ctx.name} ${ctx.lastName1} ${ctx.lastName2}.` },
  { title: '🎂 Celebraciones', text: `La familia ${ctx.lastName1} ${ctx.lastName2} celebra junta: ${ctx.allFamily}.` },

  // SITUACIONES VARIADAS (90 frases)
  { title: '✈️ De viaje', text: `Última llamada para el pasajero ${ctx.name} ${ctx.lastName1}.` },
  { title: '✈️ De viaje', text: `${ctx.parent1} pregunta: ${ctx.name}, ¿has cogido el pasaporte?` },
  { title: '✈️ De viaje', text: `Reserva de hotel a nombre de ${ctx.fullName}.` },
  { title: '✈️ De viaje', text: `${ctx.name}, no olvides hacerte fotos.` },
  { title: '✈️ De viaje', text: `Maleta de ${ctx.name} ${ctx.lastName1}: cinta número 5.` },
  { title: '✈️ De viaje', text: `Familia ${ctx.lastName1} viajando junta: ${ctx.allFamily}.` },
  { title: '✈️ De viaje', text: `${ctx.parent2} lleva a ${ctx.name} de vacaciones.` },
  { title: '✈️ De viaje', text: `${ctx.name} y ${ctx.sibling}, abrochaos el cinturón del avión.` },
  { title: '✈️ De viaje', text: `Pasaporte de ${ctx.fullName}, válido hasta 2035.` },
  { title: '✈️ De viaje', text: `${ctx.name}, guarda el equipaje en el maletero.` },
  { title: '🏥 En el médico', text: `${ctx.name} ${ctx.lastName1}, pase a la consulta 3.` },
  { title: '🏥 En el médico', text: `¿${ctx.fullName}? El doctor le está esperando.` },
  { title: '🏥 En el médico', text: `Siguiente paciente: ${ctx.name} ${ctx.lastName1} ${ctx.lastName2}.` },
  { title: '🏥 En el médico', text: `${ctx.name}, aquí tiene su receta. Cuídese.` },
  { title: '🏥 En el médico', text: `Revisión anual de ${ctx.fullName}.` },
  { title: '🏥 En el médico', text: `Historial médico del paciente ${ctx.name} ${ctx.lastName1}.` },
  { title: '🏥 En el médico', text: `${ctx.parent2} acompaña a ${ctx.name} al hospital.` },
  { title: '🏥 En el médico', text: `Cita para ${ctx.name} ${ctx.lastName1} ${ctx.lastName2} a las 10:00.` },
  { title: '🏥 En el médico', text: `Vacunación de ${ctx.name}, hijo de ${ctx.parent1}.` },
  { title: '🏥 En el médico', text: `Alta médica para ${ctx.fullName}.` },
  { title: '💼 En el trabajo', text: `${ctx.name} ${ctx.lastName1}, ¿me pasas el informe?` },
  { title: '💼 En el trabajo', text: `Les presento a ${ctx.fullName}, nuestro nuevo compañero.` },
  { title: '💼 En el trabajo', text: `${ctx.name}, excelente presentación. Felicidades.` },
  { title: '💼 En el trabajo', text: `¿Alguien sabe dónde está ${ctx.name}?` },
  { title: '💼 En el trabajo', text: `${ctx.fullName} ha sido ascendido a director.` },
  { title: '💼 En el trabajo', text: `Contrato laboral de ${ctx.name} ${ctx.lastName1} ${ctx.lastName2}.` },
  { title: '💼 En el trabajo', text: `Nómina del empleado ${ctx.fullName}.` },
  { title: '💼 En el trabajo', text: `${ctx.name}, tienes una reunión a las 15:00.` },
  { title: '💼 En el trabajo', text: `Email para ${ctx.name} ${ctx.lastName1}: proyecto aprobado.` },
  { title: '💼 En el trabajo', text: `Carta de recomendación para ${ctx.fullName}.` },
  { title: '🍕 En el restaurante', text: `Mesa reservada para ${ctx.fullName}.` },
  { title: '🍕 En el restaurante', text: `${ctx.name} ${ctx.lastName1}, ¿qué va a tomar?` },
  { title: '🍕 En el restaurante', text: `¿${ctx.name}? Su pedido está listo.` },
  { title: '🍕 En el restaurante', text: `La cuenta es para ${ctx.name} ${ctx.lastName1} ${ctx.lastName2}.` },
  { title: '🍕 En el restaurante', text: `${ctx.name} invita a ${ctx.parent1} y ${ctx.parent2}.` },
  { title: '🍕 En el restaurante', text: `Mesa familiar para ${ctx.allFamily}.` },
  { title: '🍕 En el restaurante', text: `${ctx.parent2} pide para ${ctx.name} y ${ctx.sibling}.` },
  { title: '🍕 En el restaurante', text: `Reserva a nombre de la familia ${ctx.lastName1}.` },
  { title: '🍕 En el restaurante', text: `${ctx.name}, elige lo que quieras del menú.` },
  { title: '🍕 En el restaurante', text: `Tarjeta de fidelidad de ${ctx.fullName}.` },
  { title: '☕ En la cafetería', text: `Un café con leche para ${ctx.name}.` },
  { title: '☕ En la cafetería', text: `${ctx.name} ${ctx.lastName1}, tu pedido está listo.` },
  { title: '☕ En la cafetería', text: `¿Eres ${ctx.fullName}? Aquí está tu capuccino.` },
  { title: '☕ En la cafetería', text: `${ctx.name} siempre pide lo mismo.` },
  { title: '☕ En la cafetería', text: `Para ${ctx.name} ${ctx.lastName1}, un té verde.` },
  { title: '🎬 En el cine', text: `${ctx.name}, ¿me pasas las palomitas?` },
  { title: '🎬 En el cine', text: `Dos entradas para ${ctx.fullName}. Sala 7.` },
  { title: '🎬 En el cine', text: `${ctx.name}, apaga el móvil.` },
  { title: '🎬 En el cine', text: `${ctx.parent1} lleva a ${ctx.name} y ${ctx.sibling} al cine.` },
  { title: '🎬 En el cine', text: `${ctx.name} siempre llora con las películas tristes.` },
  { title: '🎭 En el teatro', text: `Y ahora, con ustedes, ${ctx.fullName}. ¡Un aplauso!` },
  { title: '🎭 En el teatro', text: `${ctx.name}, sales en la tercera escena.` },
  { title: '🎭 En el teatro', text: `Papel protagonista: ${ctx.name} ${ctx.lastName1}.` },
  { title: '🎭 En el teatro', text: `Premio a mejor actor: ${ctx.fullName}.` },
  { title: '🎭 En el teatro', text: `${ctx.name} se sabe su papel a la perfección.` },
  { title: '🏪 De compras', text: `${ctx.name}, ¿te gusta esta camisa?` },
  { title: '🏪 De compras', text: `Tarjeta de fidelidad de ${ctx.name} ${ctx.lastName1}.` },
  { title: '🏪 De compras', text: `${ctx.name}, esto te queda genial.` },
  { title: '🏪 De compras', text: `${ctx.name} siempre encuentra las mejores ofertas.` },
  { title: '🏪 De compras', text: `Pedido online para ${ctx.fullName}.` },
  { title: '📞 Por teléfono', text: `¿Está ${ctx.name} ${ctx.lastName1}?` },
  { title: '📞 Por teléfono', text: `${ctx.name}, tienes una llamada de ${ctx.parent2}.` },
  { title: '📞 Por teléfono', text: `Hola, ¿está ${ctx.fullName} en casa?` },
  { title: '📞 Por teléfono', text: `Mensaje para ${ctx.name}: que llame urgente.` },
  { title: '📞 Por teléfono', text: `${ctx.name}, contesta el teléfono.` },
  { title: '🚗 En el coche', text: `${ctx.name}, ¿puedes mirar el GPS?` },
  { title: '🚗 En el coche', text: `Conductor: ${ctx.parent1}. Pasajeros: ${ctx.name} y ${ctx.sibling}.` },
  { title: '🚗 En el coche', text: `${ctx.name}, pon música.` },
  { title: '🚗 En el coche', text: `${ctx.name}, ¿ya hemos llegado?` },
  { title: '🚗 En el coche', text: `${ctx.parent2} conduce con ${ctx.name} de copiloto.` },
  { title: '📚 En la biblioteca', text: `${ctx.name} ${ctx.lastName1}, silencio por favor.` },
  { title: '📚 En la biblioteca', text: `Libro reservado para ${ctx.fullName}.` },
  { title: '📚 En la biblioteca', text: `${ctx.name}, devuelve los libros antes del viernes.` },
  { title: '📚 En la biblioteca', text: `${ctx.name} se pasa tardes enteras leyendo.` },
  { title: '📚 En la biblioteca', text: `Carné de biblioteca para ${ctx.name} ${ctx.lastName1} ${ctx.lastName2}.` },
  { title: '🎮 Jugando', text: `¡${ctx.name} ha ganado la partida!` },
  { title: '🎮 Jugando', text: `${ctx.name}, me toca a mí el mando.` },
  { title: '🎮 Jugando', text: `Jugador 1: ${ctx.name}. Jugador 2: ${ctx.sibling}.` },
  { title: '🎮 Jugando', text: `${ctx.name} siempre elige el personaje más rápido.` },
  { title: '🎮 Jugando', text: `Récord de ${ctx.name}: ¡100.000 puntos!` },
  { title: '🎨 Clase de arte', text: `${ctx.name}, tu dibujo ha quedado precioso.` },
  { title: '🎨 Clase de arte', text: `Primer premio para ${ctx.name} ${ctx.lastName1}.` },
  { title: '🎨 Clase de arte', text: `${ctx.name} tiene talento natural.` },
  { title: '🎨 Clase de arte', text: `${ctx.name}, ¿me prestas el pincel?` },
  { title: '🎨 Clase de arte', text: `Exposición de ${ctx.fullName}.` },
  { title: '🎵 Clase de música', text: `${ctx.name}, muy bien con el piano.` },
  { title: '🎵 Clase de música', text: `Solo de guitarra: ${ctx.name} ${ctx.lastName1}.` },
  { title: '🎵 Clase de música', text: `${ctx.name} tiene un oído excepcional.` },
  { title: '⚽ En el deporte', text: `¡Pásasela a ${ctx.name}!` },
  { title: '⚽ En el deporte', text: `${ctx.name} ${ctx.lastName1} marca el gol decisivo.` },
  { title: '⚽ En el deporte', text: `Capitán del equipo: ${ctx.name}.` }
]
